In [1]:
import numpy as np
arr_1d = np.arange(10)
print(arr_1d)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
arr_2d = np.random.randint(0, 9, size=(3, 4))
print(arr_2d)


[[7 5 6 0]
 [3 0 5 7]
 [6 2 1 0]]


In [3]:
reshape = arr_2d.reshape(4, 3)
print(reshape)


[[7 5 6]
 [0 3 0]
 [5 7 6]
 [2 1 0]]


In [4]:
arr_1d[2]

2

In [5]:
arr_2d[:, -2:]


array([[6, 0],
       [5, 7],
       [1, 0]])

In [ ]:
matrix_3x3 = np.arange(9).reshape(3, 3)
diagonal_elements = np.diagonal(matrix_3x3)
print(diagonal_elements)

In [ ]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])
element_wise_multiplication = np.multiply(arr_a, arr_b)
print(element_wise_multiplication)


In [ ]:
mean = np.mean(arr_1d)
median = np.median(arr_1d)
std_dev = np.std(arr_1d)
print(f"Mean: {mean}, Median: {median}, Standard Deviation: {std_dev}")


In [ ]:
normalized_array = (arr_1d - np.min(arr_1d)) / (np.max(arr_1d) - np.min(arr_1d))
print(normalized_array)

In [ ]:
np.concatenate((arr_1d, arr_1d, arr_1d))

In [ ]:
np.where(arr_1d % 2 == 0, -arr_1d, arr_1d)

In [ ]:
constant_value = 5
array_2D_modified = arr_2d + constant_value
print(array_2D_modified)


In [ ]:
arr_2d_modified = arr_2d + 2
print(arr_2d_modified)


In [ ]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_c = np.add(matrix_a, matrix_b)
print(matrix_c)


In [ ]:
matrix_d = np.subtract(matrix_a, matrix_b)
print(matrix_d)

In [ ]:
scalar = 3
matrix_e = np.multiply(matrix_a, scalar)
print(matrix_e)
